name: CI

on:
  # Avvia la CI ad ogni push su develop
  push:
    branches: [ develop ]

  # Avvia la CI su qualunque PR che punta a main
  pull_request:
    branches: [ main ]

  # Avvio manuale dalla tab Actions
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q